import Content from "./Content";
import data from "@/public/data.json";

export const metadata = {
  title: "Country Searcher",
  description: "Generated by create next app",
};

export default function Page({ params }: { params: { country: string } }) {
  data.forEach((el) =>
    el.alpha3Code == params.country
      ? (metadata.title = `Country Searcher | ${el.name}`)
      : null
  );

  return <Content />;
}
